class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start1'
        self.MirrorCommand = 'dl1'
        self.UnzipMirrorCommand = 'unzip1'
        self.TarMirrorCommand = 'tar1'
        self.ZipMirrorCommand = 'zip1'
        self.CancelMirror = 'batal1'
        self.CancelAllCommand = 'batalin1'
        self.ListCommand = 'cari1'
        self.StatusCommand = 'status1'
        self.AuthorizedUsersCommand = 'users1'
        self.AuthorizeCommand = 'auth1'
        self.UnAuthorizeCommand = 'unauth1'
        self.AddSudoCommand = 'addsudo1'
        self.RmSudoCommand = 'rmsudo1'
        self.PingCommand = 'ping1'
        self.RestartCommand = 'restart1'
        self.StatsCommand = 'stat1'
        self.HelpCommand = 'bantuan1'
        self.LogCommand = 'log1'
        self.SpeedCommand = 'speedtest1'
        self.CloneCommand = 'salin1'
        self.CountCommand = 'hitung1'
        self.WatchCommand = 'watch1'
        self.TarWatchCommand = 'tarwatch1'
        self.DeleteCommand = 'del1'
        self.ConfigMenuCommand = 'config1'
        self.ShellCommand = 'shell1'
        self.UpdateCommand = 'update1'
        self.ExecHelpCommand = 'exechelp1'
        self.TsHelpCommand = 'tshelp1'

BotCommands = _BotCommands()
