class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start3'
        self.MirrorCommand = 'dl3'
        self.UnzipMirrorCommand = 'unzip3'
        self.TarMirrorCommand = 'tar3'
        self.ZipMirrorCommand = 'zip3'
        self.CancelMirror = 'batal3'
        self.CancelAllCommand = 'batalin3'
        self.ListCommand = 'cari3'
        self.StatusCommand = 'status3'
        self.AuthorizedUsersCommand = 'users3'
        self.AuthorizeCommand = 'auth3'
        self.UnAuthorizeCommand = 'unauth3'
        self.AddSudoCommand = 'addsudo3'
        self.RmSudoCommand = 'rmsudo3'
        self.PingCommand = 'ping3'
        self.RestartCommand = 'restart3'
        self.StatsCommand = 'stat3'
        self.HelpCommand = 'bantuan3'
        self.LogCommand = 'log3'
        self.SpeedCommand = 'speedtest3'
        self.CloneCommand = 'salin3'
        self.CountCommand = 'hitung3'
        self.WatchCommand = 'watch3'
        self.TarWatchCommand = 'tarwatch3'
        self.DeleteCommand = 'del3'
        self.ConfigMenuCommand = 'config3'
        self.ShellCommand = 'shell3'
        self.UpdateCommand = 'update3'
        self.ExecHelpCommand = 'exechelp3'
        self.TsHelpCommand = 'tshelp3'

BotCommands = _BotCommands()
